### ISSUE TITLE
Chalk wall supposed to look like grass?

### ISSUE THREAD

**Issue by wybo** [jecowa/Meph#3]
![chalk_wall_grassy](https://user-images.githubusercontent.com/617891/39405814-83b74190-4ba4-11e8-98cc-2e0677c67a1e.png)

Is the chalk wall supposed to look this much like grass? Seems like a glitch to me...

**Comment by jecowa** [comment]
Probably not. I'm looking into it. The screenshot and name of the messed up tile was really helpful

**Comment by jecowa** [comment]
I left off a line that added all the new wall stuff in the overrides.txt file. `
[TILESET:_MDF_decorations_3.png:_MDF_decorations_3.png:_MDF_overrides_6]`

Thank you!

**Comment by wybo** [comment]
Works great now. Minerals and smoothed walls also look all good now. Thanks for fixing!
